### ISSUE TITLE
Copy to clipboard, utility/application terminates

### ISSUE THREAD

**Issue by jkokoska** [deadlydog/PathLengthChecker#10]
After generating data output, when clicking on Copy Paths to Clipboard
I receive an exception (Oxe0434352) occurred in the application at location 0x755f4e28.

'the application has stopped working'.

**Comment by deadlydog** [comment]
Hmmm, that's odd. Can you provide any other information, such as which version of Windows you are running, and if it's a problem all the time or not; Does it crash consistently, even with different result (path) sets?

**Comment by deadlydog** [comment]
I wasn't able to reproduce this issue, but changes were made in #24 to make copying to the clipboard more thread-safe, so it may have addressed this. I'm going to close this for now, as it will hopefully be fixed in the next release v1.3+.
