### ISSUE TITLE
Add a drag and drop to the GUI executable

### ISSUE THREAD

**Issue by wvxwxvw** [deadlydog/PathLengthChecker#36]
Add a drag and drop to the GUI executable. Then it will be possible to add a program item to the file manager context menu or as a button to the file manager panel.  
  
Opening parameters are needed, such as `PathLengthCheckerGUI.exe "D:\folder"`

**Comment by deadlydog** [comment]
Hmmm, I haven't done what you're asking for before, and don't have a bunch of free time atm (plus, I have many other open source projects to support :P ). I'd be open accepting a pull request if you're inclined to create one :)

**Comment by wvxwxvw** [comment]
@deadlydog 
Unfortunately, I can't help you with anything. And this is a standard function for absolutely all programs, with the exception of completely homemade ones. I.e. must try very hard to find a program without command line support, and not vice versa.

**Comment by deadlydog** [comment]
Thanks to @mwanchap this is now available in v1.6.0 👏🎉🙌
