### ISSUE TITLE
Resizable GUI

### ISSUE THREAD

**Issue by Kolky** [deadlydog/PathLengthChecker#4]
When you try to resize (or maximize) the GUI, the DataGrid won't scale. This is because you've build the GUI using margin's instead of actual Grid Column/Row definitions. Would be nice to have a scaleable resizable GUI!

Thanks

**Comment by deadlydog** [comment]
I accepted your pull request @Kolky and then refactored it quite a bit. Regardless, v1.2.0 now supports a resizable GUI. Thanks!

**Comment by Kolky** [comment]
Did not have the time to do it myself, great work!
