### ISSUE TITLE
Feature requests: Remember windows size+position, Min+max path length and font

### ISSUE THREAD

**Issue by pstein** [deadlydog/PathLengthChecker#44]
Whenever I start PLC it starts with initial values.

PLC should remember the last window size and position on desktop and min+max path length.

Furthermore I would appreciate if I could select another font (=a monospaced font)

Can you add it in the next release?

Thank you

**Comment by aferrazlr** [comment]
+1 for monospace font

**Comment by deadlydog** [comment]
What font did you guys have in mind @pstein and @aferrazlr ? And do you want all of the fonts changed, or just the font of the grid that displays the paths?

**Comment by mwanchap** [comment]
Asking a group of developers which monospaced font is the best? Are you sure you want to invite such controversy 😅
After all, it's _obviously_ Cascadia Code.
\*hides under desk until the yelling stops\*
Perhaps a font selector instead?

**Comment by deadlydog** [comment]
Haha, yeah, I was really just wanting to know if they thought the app would look better if everything was monospaced, but I'm going to assume they were just looking for the paths shown in the grid to be monospaced to easily tell which ones were longer. Also, I need to go with a font that everyone will have installed, so I'm just going to go with Courier New, as every Windows machine should have that installed.

We could provide a font selector, but I think that's overkill for a small utility app like this :)

**Comment by deadlydog** [comment]
Ok, all issues should be addressed in v1.8.0. Enjoy! :)
