### ISSUE TITLE
Must copy the list of paths in sorted form

### ISSUE THREAD

**Issue by wvxwxvw** [deadlydog/PathLengthChecker#53]
The program has sorting by columns. It is expected that the program should copy the list in sorted form. Again, a flaw. ) Again, after copying the list, the user needs to use third-party software to Refine the list. This should not be the case, the program should output the list ready for use. That is. as the user currently sees it, and not just randomly.

**Comment by deadlydog** [comment]
Thanks for reporting the feature request. PRs and donations are welcomed :)

**Comment by deadlydog** [comment]
This has been implemented in v1.9.1. Thanks for the suggestion. Also, someone donated $5 to me; if it was you @wvxwxvw thank you! :)
