### ISSUE TITLE
v1.11.4 zip file empty

### ISSUE THREAD

**Issue by Shaken-K1W1** [deadlydog/PathLengthChecker#62]
The v1.11.4.zip file downloads with no files in it.

Anyway
Thanks for this amazing utility. 
The GUI made things fast and painless. v1.11.1

**Comment by deadlydog** [comment]
Thanks for reporting this. Looks like it's an issue with GitHub; I noticed the same issue in the [GrepWin repos](https://github.com/stefankueng/grepWin) releases a few weeks back, although it looks like it's working properly now for them.

Re-uploading my artifact's zip file still results in the same issue where when I download it from GitHub it's empty. I guess we just need to wait for GitHub to fix it....

**Comment by deadlydog** [comment]
I've [opened this ticket](https://support.github.com/ticket/personal/0/1035434) with GitHub support to look into this issue. I'm not sure if you'll be able to view that link though, or if it's public. I'll report back here when I have an update. Thanks.

**Comment by deadlydog** [comment]
Looks like it's just the browser blocking the download for some reason. Strange that it works for the previous version's zip file ¯\_(ツ)_/¯

This was my reply to GitHub support after they told me to try using a different browser or the command line to download the zip file.

> Yes, you are correct. I was using Firefox and it was also blocking the download (kind of, it created an empty zip file). I switched to Chrome, saw the warning, and told it to allow the download and that worked. Going back to Firefox, there was no prompt that it was blocking the download and the zip file did get created, but going into the downloaded items, and then clicking More Info on the item, it showed the "Allow" / "Remove" options. After clicking Allow it worked in Firefox as well. Looks like both Chrome and Firefox did an update recently that caused this confusion.
> 
> Thanks for the help, and sorry for wasting your time when it wasn't a GitHub issue at all.

I'm going to close this issue, but if you're still seeing the problem after reading this, feel free to reopen this. Thanks!
