### ISSUE TITLE
Change the use different name instead of "Root directory"

### ISSUE THREAD

**Issue by vasili111** [deadlydog/PathLengthChecker#7]
This is a useful utility that can be useful for non-advanced users too. For many non-advanced Windows users "root" can be confusing. Also in the Windows world "folder" is preferable than a "directory". 
I suggest to rename "Root directory" to something like "Starting folder", "Start in folder" or etc.

**Comment by deadlydog** [comment]
I have renamed "Root Directory" to "Starting Directory" in the UI, as well as added and updated some tooltips, so that should address this concern I believe. Closing this issue. The changes should be in v1.3+.
