### ISSUE TITLE
Adopt/create an icon

### ISSUE THREAD

**Issue by teknowledgist** [deadlydog/PathLengthChecker#9]
Not much to say.  A nice icon to represent this nice program would be nice.  :smile:

**Comment by deadlydog** [comment]
I'm open to icon suggestions and pull requests ;)

**Comment by deadlydog** [comment]
Thanks! I converted your image to a .ico and set it as the application image, but it ended up looking pretty horrible when getting shrunk down so small. I liked your measuring tape idea though and found a basic free measuring tape icon. I've made the change and pushed it to source control, but haven't made a new release for it yet. It will be included in the next release (v1.3.0+). Thanks for the idea and going through the trouble of making an image! :)
